export interface ActorInput {
  host?: string;
  port?: number;
  logLevel?: "DEBUG" | "INFO" | "WARNING" | "ERROR";
  requiredEnvVars?: string[];
  apiKeyEnabled?: boolean;
  apiKey?: string;
  browserPoolEnabled?: boolean;
  browserPoolSize?: number;
  browserHeadless?: boolean;
  browserLaunchTimeoutMs?: number;
  standbyEnabled?: boolean;
  standbyIdleTimeoutMs?: number;
  standbyTickIntervalMs?: number;
  standbyRecycleAfterMs?: number;
  sessionStorageEnabled?: boolean;
  sessionStoreName?: string;
  sessionStoreKeyPrefix?: string;
  requestQueueConcurrency?: number;
  requestQueueMaxSize?: number;
  requestQueueTaskTimeoutMs?: number;
  fetchTimeoutDefaultMs?: number;
  fetchTimeoutMinMs?: number;
  fetchTimeoutMaxMs?: number;
  requestBodyMaxBytes?: number;
  cacheProvider?: "memory" | "redis";
  cacheTtlMs?: number;
  cacheStaleTtlMs?: number;
  cacheSwrEnabled?: boolean;
  redisUrl?: string;
  redisKeyPrefix?: string;
  fastModeEnabled?: boolean;
  fastModeMaxFields?: number;
  prewarmEnabled?: boolean;
  prewarmIntervalMs?: number;
  prewarmTargets?: Array<Record<string, unknown>>;
  browserOptimizedFlagsEnabled?: boolean;
  browserBlockResources?: boolean;
  proxyRotationEnabled?: boolean;
  proxyPoolUrls?: string[];
  proxyQuarantineMs?: number;
  fingerprintRotationEnabled?: boolean;
  retryMaxAttempts?: number;
  retryBaseDelayMs?: number;
  retryMaxDelayMs?: number;
  retryBlockedDelayMs?: number;
  retryJitterMs?: number;
  circuitBreakerEnabled?: boolean;
  circuitFailureThreshold?: number;
  circuitOpenMs?: number;
  circuitHalfOpenSuccessThreshold?: number;
  sourceQuarantineMs?: number;
  fallbackUrlStrategyEnabled?: boolean;
  checkpointMaxEntries?: number;
  deadLetterEnabled?: boolean;
  deadLetterStoreName?: string;
  deadLetterMaxEntries?: number;
  incidentBlockedSpikeThreshold?: number;
  incidentBlockedSpikeWindowMs?: number;
  incidentWebhookUrl?: string;
  shutdownDrainTimeoutMs?: number;
  mockFetchDelayMs?: number;
}

export interface RuntimeConfig {
  host: string;
  port: number;
  logLevel: "DEBUG" | "INFO" | "WARNING" | "ERROR";
  apiKeyEnabled: boolean;
  apiKey: string | null;
  browserPoolEnabled: boolean;
  browserPoolSize: number;
  browserHeadless: boolean;
  browserLaunchTimeoutMs: number;
  standbyEnabled: boolean;
  standbyIdleTimeoutMs: number;
  standbyTickIntervalMs: number;
  standbyRecycleAfterMs: number;
  sessionStorageEnabled: boolean;
  sessionStoreName: string;
  sessionStoreKeyPrefix: string;
  requestQueueConcurrency: number;
  requestQueueMaxSize: number;
  requestQueueTaskTimeoutMs: number;
  fetchTimeoutDefaultMs: number;
  fetchTimeoutMinMs: number;
  fetchTimeoutMaxMs: number;
  requestBodyMaxBytes: number;
  cacheProvider: "memory" | "redis";
  cacheTtlMs: number;
  cacheStaleTtlMs: number;
  cacheSwrEnabled: boolean;
  redisUrl: string | null;
  redisKeyPrefix: string;
  fastModeEnabled: boolean;
  fastModeMaxFields: number;
  prewarmEnabled: boolean;
  prewarmIntervalMs: number;
  prewarmTargets: Array<Record<string, unknown>>;
  browserOptimizedFlagsEnabled: boolean;
  browserBlockResources: boolean;
  proxyRotationEnabled: boolean;
  proxyPoolUrls: string[];
  proxyQuarantineMs: number;
  fingerprintRotationEnabled: boolean;
  retryMaxAttempts: number;
  retryBaseDelayMs: number;
  retryMaxDelayMs: number;
  retryBlockedDelayMs: number;
  retryJitterMs: number;
  circuitBreakerEnabled: boolean;
  circuitFailureThreshold: number;
  circuitOpenMs: number;
  circuitHalfOpenSuccessThreshold: number;
  sourceQuarantineMs: number;
  fallbackUrlStrategyEnabled: boolean;
  checkpointMaxEntries: number;
  deadLetterEnabled: boolean;
  deadLetterStoreName: string;
  deadLetterMaxEntries: number;
  incidentBlockedSpikeThreshold: number;
  incidentBlockedSpikeWindowMs: number;
  incidentWebhookUrl: string | null;
  shutdownDrainTimeoutMs: number;
  mockFetchDelayMs: number;
}
